import { Inter as FontSans } from "next/font/google";
import "@/styles/globals.css";
import { Provider } from "@/components/provider/Provider";

const fontSans = FontSans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fontSans.className}>
        <Provider>{children} </Provider>
      </body>
    </html>
  );
}
