### get all data from api 
GET http://localhost:3000/api/users


### get all user by role from api 
GET http://localhost:3000/api/users?role=vendor

### post data api 
POST http://localhost:3000/api/users

{
    "nama": "fikry haykal",
    "email": "fikryhaykal@gmail.com",
    "password": "123456",
    "phone" :"0811007008",
    "role" : "vendor"
}


POST http://localhost:3000/api/users/register

{
    "nama": "fikry haykal",
    "email": "fikryhaykal@gmail.com",
    "password": "123456",
    "phone" :"0811007008",
    "role" : "vendor"
}


### delete data api 
DELETE http://localhost:3000/api/users/873d1070-7517-4435-9922-a06ae5a72afe


### find data api 
GET http://localhost:3000/api/users/424193d1-e053-4641-898a-6f61172e1e9b


### update data api 
PATCH http://localhost:3000/api/users/873d1070-7517-4435-9922-a06ae5a72afe

{
   "nama": "M Fikry Haykal"
}

### update data api 
PATCH http://localhost:3000/api/users/dadfd8cf-bff7-4545-bfe2-8295161ccb39

{
   "nama": "Fulan ABC"
}

###tes login
POST http://localhost:3000/api/users/login

{
    "email": "fikryhaykal@gmail.com",
    "password": "123456"
}